ARG FROMTAG ${FROMTAG}
FROM registry.redhat.io/openshift4/dpdk-base-rhel8:${FROMTAG}
#https://catalog.redhat.com/software/containers/openshift4/dpdk-base-rhel8/5e32be6cdd19c77896004a41?container-tabs=overview

COPY start-testpmd.sh /usr/local/bin/
COPY jq /usr/local/bin/
WORKDIR /opt/
